version: '3.8'
services:
  db:
    image: postgres:16.1-alpine
    ports:
      - ${PGPORT_EXTERNAL}:5432
    environment:
      TZ: 'Asia/Almaty'
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/:/var/lib/postgresql/data
    restart: unless-stopped

  nest:
    image: node:20.11.1
    depends_on:
    - db
    command: bash -c "npm install && npm run typeorm migration:run -- -d src/data-source.ts && npm run start:dev"
    working_dir: /app
    volumes:
      - ./nest/:/app
    ports:
      - 3000:3000
    environment:
      TZ: 'Asia/Almaty'
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      APP_URL: ${APP_URL}
      APP_PORT: ${APP_PORT}
      WEB_URL: ${WEB_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    restart: unless-stopped
