version: '3.8'
services:
  mongo:
    image: mongo:7.0.7
    volumes:
      - ./mongo/:/data/db/
    ports:
      - ${MONGOPORT_EXTERNAL}:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  db:
    image: postgres:16.1-alpine
    ports:
      - ${PGPORT_EXTERNAL}:5432
    environment:
      TZ: 'Asia/Almaty'
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/:/var/lib/postgresql/data
    restart: unless-stopped

  cache:
    image: redis:7.2.4
    # command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    command: redis-server --maxmemory 1GB --maxmemory-policy volatile-lru --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./cache/:/data
    ports:
      - ${REDISPORT_EXTERNAL}:6379

  nest:
    image: node:20.11.1
    depends_on:
    - db
    - mongo
    - cache
    command: bash -c "npm install && npm run typeorm migration:run -- -d src/data-source.ts && npm run start:dev"
    working_dir: /app
    volumes:
      - ./nest/:/app
    ports:
      - 3000:3000
    environment:
      TZ: 'Asia/Almaty'
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      APP_URL: ${APP_URL}
      APP_PORT: ${APP_PORT}
      WEB_URL: ${WEB_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    restart: unless-stopped
